version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - mm-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - mm-network

  # --- BACKEND API (FastAPI) ---
  api:
    build: .
    container_name: api
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./app/detector/modele_fraude.pkl:/app/app/detector/modele_fraude.pkl:ro
      - ./moneyshield.db:/app/moneyshield.db
      - .:/app # Hot reload dev
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    networks:
      - mm-network

  # --- WORKERS & DASHBOARD ---
  generator:
    build: .
    container_name: generator
    command: python -m app.generator.generateur
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    networks:
      - mm-network
    restart: unless-stopped

  detector:
    build: .
    container_name: detector
    command: python -m app.detector.detecteur
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    volumes:
      - ./app/detector/modele_fraude.pkl:/app/app/detector/modele_fraude.pkl:ro
      - ./moneyshield.db:/app/moneyshield.db
    networks:
      - mm-network
    restart: unless-stopped

  dashboard:
    build: .
    container_name: dashboard
    command: streamlit run app/dashboard/dashboard.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - ./moneyshield.db:/app/moneyshield.db
      - .:/app # Hot reload dev
    networks:
      - mm-network
    restart: unless-stopped

networks:
  mm-network:
    driver: bridge